MAX_FILES: 300
SERVICE_NAME: "Amazon EKS"
MARKDOWN_DIRECTORY: "input-markdown"
OUTPUT_CSV_FILE: "output/claude-tcx3-eks-v4.csv"
LOGGING_DIR: "output/logs"
MAX_WORKERS: 20
CONSOLE_LOGS_ENABLED: false
BEDROCK_MODEL: "anthropic.claude-3-sonnet-20240229-v1:0"